# [START django_app]
runtime: python38
handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: static/

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto
# [END django_app]
entrypoint: gunicorn -b :$PORT wsgi
env_variables:
  ENV: "prod"
  GCS_PROJECT_NAME: "mobile-bnb"
  GCS_BUCKET_NAME: "mobile-bnb-storage"
  BACKEND_SECRET_KEY: "gy*5t35=vo&9d9%7_)x#m=ufie(qv#l_a3)nztsiw*lb$pv#4h"
  FRONTEND_ENDPOINT_URL: "https://frontend-dot-mobile-bnb.uc.r.appspot.com"
  DB_HOST: "172.17.33.4"
  DB_PORT: "5432"
  DB_USER: "mobile_test"
  DB_PASSWORD: "orkpower78"
  EMAIL_HOST: "mail.engulfing.com"
  EMAIL_PORT: 587
  EMAIL_HOST_USER: "mobilebnb@engulfing.com"
  EMAIL_HOST_PASSWORD: "orkpower78"
