# Generated by Django 3.1.2 on 2020-11-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
