# Generated by Django 3.1.2 on 2020-12-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_auto_20201117_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='photos',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
