# Generated by Django 3.1.3 on 2020-11-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_auto_20201117_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
