# Generated by Django 3.1.2 on 2020-12-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_mobile_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.jpg', upload_to='media')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mobiles.mobile')),
            ],
        ),
    ]
