# Generated by Django 3.1.4 on 2020-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_auto_20201202_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos'),
        ),
    ]
