# Generated by Django 3.1.4 on 2020-12-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0005_auto_20201204_1335'),
        ('mobiles', '0003_mobile_location'),
    ]

    operations = [
    ]
