# Generated by Django 3.1.3 on 2020-12-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0008_mobile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
