# Generated by Django 3.1.3 on 2020-12-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0010_remove_mobile_state'),
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begindate', models.DateField()),
                ('enddate', models.DateField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='BlockingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begindate', models.DateField()),
                ('enddate', models.DateField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobile')),
            ],
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
