# Generated by Django 3.1.4 on 2020-12-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201103_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
